# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stripr < Formula
  desc ""
  homepage "https://github.com/aosasona/homebrew-pkgs"
  version "0.1.13"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aosasona/stripr/releases/download/v0.1.13/stripr_0.1.13_Darwin_arm64.tar.gz"
      sha256 "7301599fcbc50413d0b7fac5819fe8d0be6e9810b5b3c4fcc0fe4cbd50f74b83"

      def install
        bin.install "stripr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/stripr/releases/download/v0.1.13/stripr_0.1.13_Darwin_x86_64.tar.gz"
      sha256 "bdcf81e28c9ef10319a2addb475307e70b6add6198145efdbfc11702119c6130"

      def install
        bin.install "stripr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aosasona/stripr/releases/download/v0.1.13/stripr_0.1.13_Linux_arm64.tar.gz"
      sha256 "87626a597832e58475a20b9829f3155c4048cd7fa073a16da2c139b3fd784686"

      def install
        bin.install "stripr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/stripr/releases/download/v0.1.13/stripr_0.1.13_Linux_x86_64.tar.gz"
      sha256 "87d7b8fb2700de38cab0aa6bd63b1a5c7ea1957838a24269fa062720ce609f85"

      def install
        bin.install "stripr"
      end
    end
  end
end
