# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stripr < Formula
  desc ""
  homepage "https://github.com/aosasona/homebrew-pkgs"
  version "0.1.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/stripr/releases/download/v0.1.14/stripr_0.1.14_Darwin_x86_64.tar.gz"
      sha256 "596bc86e1c2833fc3d8469ed9e9f81749493ae8166964dbaee1d7b04970c6298"

      def install
        bin.install "stripr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aosasona/stripr/releases/download/v0.1.14/stripr_0.1.14_Darwin_arm64.tar.gz"
      sha256 "045b7d34632ad13eafb73c732012fd2843695df20c826662d5fa1f705df673f9"

      def install
        bin.install "stripr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aosasona/stripr/releases/download/v0.1.14/stripr_0.1.14_Linux_x86_64.tar.gz"
      sha256 "8e0490a68e2f572326de0d13574063f1178e2f6fa38f62e77d38737af129041e"

      def install
        bin.install "stripr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aosasona/stripr/releases/download/v0.1.14/stripr_0.1.14_Linux_arm64.tar.gz"
      sha256 "8daf53219597517fbef9ab0ab879232c06d5143a9c9e4d45b875883d31227ce2"

      def install
        bin.install "stripr"
      end
    end
  end
end
